defaults: &defaults
  adapter: postgresql
  username: deliverables_schedule
  password: 
  encoding: unicode
  host: localhost

development:
  <<: *defaults
  database: deliverables_schedule_development

test: &test
  <<: *defaults
  database: deliverables_schedule_test

production:
  <<: *defaults
  database: deliverables_schedule_development

cucumber:
  <<: *defaults
  database: deliverables_schedule_test